from __future__ import annotations

import smtplib
from email.message import EmailMessage
from typing import Any

from backend.app.core.config import get_settings


def build_proof_email(negotiation: dict[str, Any], turns: list[dict[str, Any]]) -> dict[str, str]:
    result = negotiation.get("result") or {}
    issue = negotiation.get("issueContext") or {}
    company = issue.get("companyName") or negotiation.get("provider") or "the company"
    subject = f"RateDrop proof: {company} outcome"
    lines = [
        "RateDrop proof report",
        "",
        f"Company: {company}",
        f"Status: {negotiation.get('status', 'unknown')}",
        f"Summary: {result.get('summary', 'Support mission completed.')}",
    ]

    if issue:
        lines.extend(
            [
                "",
                "Mission",
                f"Problem: {issue.get('problemSummary', '')}",
                f"Desired outcome: {issue.get('desiredOutcome', '')}",
            ]
        )

    transcript_summary = result.get("transcriptSummary") or []
    if transcript_summary:
        lines.extend(["", "Proof trail"])
        lines.extend(f"- {item}" for item in transcript_summary)

    if turns:
        lines.extend(["", "Transcript"])
        for turn in turns:
            speaker = "RateDrop" if turn.get("role") == "negotiator" else "Representative"
            lines.append(f"{speaker}: {turn.get('text', '')}")

    lines.extend(["", "Generated by RateDrop."])
    return {"subject": subject, "body": "\n".join(lines)}


def send_proof_email(to_email: str, proof: dict[str, str]) -> dict[str, Any]:
    settings = get_settings()
    if not settings.smtp_configured:
        return {
            "sent": False,
            "reason": "SMTP is not configured.",
            "subject": proof["subject"],
            "body": proof["body"],
        }

    message = EmailMessage()
    message["Subject"] = proof["subject"]
    message["From"] = settings.smtp_from_email or ""
    message["To"] = to_email
    message.set_content(proof["body"])

    with smtplib.SMTP(settings.smtp_host or "", settings.smtp_port, timeout=20) as smtp:
        smtp.starttls()
        smtp.login(settings.smtp_username or "", settings.smtp_password or "")
        smtp.send_message(message)

    return {"sent": True, "to": to_email, "subject": proof["subject"]}
